import '../../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { i18n } from '@/config/i18n.config';
import { Nav } from '@/components/Nav';
import { Flowbite, ThemeModeScript } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
    const languages = i18n.locales.map((lang) => ({ lang }));
    return languages;
}

export const metadata: Metadata = {
    title: "YouTube Piloto",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: { lang: string };
}) {
    return (
        <html lang={params.lang}>
            <head>
                <ThemeModeScript />
            </head>
            <body className={inter.className}>
                <Flowbite>
                    <Nav />
                    {children}
                </Flowbite>
            </body>
        </html>
    );
}
